### ISSUE TITLE
multi-line and ESS

### ISSUE THREAD

**Issue by lambiase** [IvanMalison/multi-line#1]
Hi Ivan,

first of all, thanks for making multi-line available. I was thinking of writing my own package for operations similar to expand-\* or contract-\* in js2-refactor for other languages, but I am happy that you worked on it :+1: )

I just tested multi-line with [ESS](http://ess.r-project.org/), and it works fine without any special configuration.

For example, calling multi-line within the round brackets:

``` R
foo <- function(bar, baz, qzy = 1) {
  a = 1
}
```

produces

``` R
foo <- function(
                bar,
                baz,
                qzy = 1
                ) {
  a = 1
}
```

However, I would rather prefer something like

``` R
foo <- function(bar,
                baz,
                qzy = 1) {
  a = 1
}
```

i.e. skipping the first and the last newline.

I guess I would need to create my own multi-line-master-strategy for ess-mode, but I am not quite sure about how to proceed.

**Comment by colonelpanic8** [comment]
You're in luck. There is already a strategy (its not really its own class just a set of arguments that you pass to a class) for multi-lining in the way that you want to. It looks like you want a new line for every argument, but you don't want a new line between the first argument and the parentheses or a new line between the last argument and the parentheses. The way to get that is:

```
(defvar lambiase-strategy
  (make-instance
   multi-line-strategy
   :respace (multi-line-clearing-reindenting-respacer
             (make-instance multi-line-always-newline
                            :skip-first t
                            :skip-last t))))
```

If you want this type of indenting to be in effect by default, you would then execute:

```
(multi-line-set-default-strategy multi-line-master-strategy lambiase-strategy)
```

If you wanted it to be active only in `ess-mode`:

```
(multi-line-set-strategy multi-line-master-strategy 'ess-mode lambiase-strategy)
```

I know that this is a pretty complicated bit of configuration, and I'm trying to think of ways to make this easier without losing flexibility or power. suggestions are welcome

**Comment by colonelpanic8** [comment]
> I just tested multi-line with ESS, and it works fine without any special configuration.

How extensively did you test it?

Should I add it to the list of officially supported major-modes?

**Comment by lambiase** [comment]
It works like a charm, thanks a lot!

**Comment by lambiase** [comment]
Well, I can't say that I tested a lot. From the quick tests I have done, it works as expected for R and S+ code.
However, ESS also supports  
- SAS
- OpenBUGS/JAGS
- Stata
- Julia

but I am not familiar with any of those languages. I will experiment some more with R and S+ and let you know if I experience any issue.
