### ISSUE TITLE
`multi-line-candidate` is a void variable in IvanMalison/mutli-line@7c5fbae

### ISSUE THREAD

**Issue by bryce-carson** [IvanMalison/multi-line#18]
#17 introduces a `void-variable` error in Emacs 27.2.

I opened an issue on the Spacemacs repo for this. Please refer to syl20bnr/spacemacs#15255 for discussion of the issue and the [backtrace](https://gist.github.com/bryce-carson/3b98231cf0a3ea79f5bee1802dcccbb3).

**Comment by bryce-carson** [comment]
I'm closing this issue for now, because vanilla Emacs 27.2 has no issue installing multi-line from MELPA, or using the function bound to "C-c d" as in the instructions of `multi-line`. The issue is likely limited to Spacemacs.

**Comment by thanhvg** [comment]
I can confirm the problem on Spacemacs. 

We byte-compile all the packages. And in the [17](https://github.com/IvanMalison/multi-line/pull/17)  `ieio`  breaks byte compilation.  `(require 'eioio)` should be kept  for at least  `defclass` to be recognized. `(require 'cl-lib)` won't bring `defclass` in.
