### ISSUE TITLE
please don't break master

### ISSUE THREAD

**Issue by wbolster** [IvanMalison/multi-line#7]
hi,

since melpa packages a `master` snapshot automatically, it would be great if you committed non-functional work in progress to a development branch, since it seems like the latest melpa package is (or at least was) broken for a while.

**Comment by colonelpanic8** [comment]
master was broken? I added a test suite that should catch any issues. Which commit was on master that was broken.

I'll try to write a test that would fail on that issue.

**Comment by wbolster** [comment]
@rjprins do you still have those error messages?

**Comment by colonelpanic8** [comment]
I'm assuming that things are currently working on master, so I'm going to close this issue for now.

@wbolster @rjprins master was broken for emacs24 a couple of weeks ago
see https://github.com/IvanMalison/multi-line/issues/3

as I mentioned before, I added a travis CI build that runs in both emacs25 and emacs24, so it shouldn't happen again.

If you are concerned about stability, I should mention that there is a melpa-stable version of multi-line available!
